/*
 *  Copyright (c) 2020 Rally Tactical Systems, Inc.
 *  All rights reserved.
 */

#ifndef MAGELLANAPI_H
#define MAGELLANAPI_H

#include "MagellanTypes.h"
#include "MagellanConstants.h"

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @brief [SYNC] Initializes the Magellan library.
 *
 * Call this function to initialize the library prior starting main operation.
 *
 * No events are generated by this API call.
 *
 * @param configuration An optional JSON object containing configuration
 *
 * @return MAGELLAN_RESULT_OK if successful
 *
 * @see magellanShutdown()
 */
MAGELLAN_API int magellanInitialize(const char * _Nullable configuration);


/**
 * @brief [SYNC] Shuts down the Magellan library.
 *
 * Calling this function will carry out the inverse of magellanInitialize().  Typically this 
 * function is called as part of the application shutdown procedure or when a full restart of the 
 * library is required.
 *
 * Furthermore, as this is a synchronous function call, the application should take care
 * to call it from a thread that will not be impacted by a delay in processing.
 *
 * No events are generated by this API call.
 *
 * @return MAGELLAN_RESULT_OK if successful
 * @see magellanInitialize()
*/
MAGELLAN_API int magellanShutdown();


/**
 * @brief [SYNC] Installs a callback function to be called for logging
 *
 * No events are generated by this API call.
 *
 * @return MAGELLAN_RESULT_OK if successful
 * @see magellanLogMessage()
*/
MAGELLAN_API int magellanSetLoggingHook(PFN_MAGELLAN_LOGGING_HOOK hookFn);


/**
 * @brief [SYNC] Logs a message using the currenbtly active logger.
 *
 * No events are generated by this API call.
 *
 * @return None
 * @see magellanSetLoggingHook()
*/
MAGELLAN_API void magellanLogMessage(int level, const char * _Nonnull tag, const char * _Nonnull msg);

MAGELLAN_API int magellanBeginDiscovery(const char * _Nullable serviceType, 
                                        MagellanToken_t * _Nonnull pToken,
                                        PFN_MAGELLAN_DISCOVERY_FILTER_HOOK hookFn,
                                        const void * _Nullable userData);

MAGELLAN_API int magellanEndDiscovery(MagellanToken_t token);

MAGELLAN_API int magellanPauseDiscovery(MagellanToken_t token);

MAGELLAN_API int magellanResumeDiscovery(MagellanToken_t token);

MAGELLAN_API void magellanSetTalkgroupCallbacks(PFN_MAGELLAN_ON_NEW_TALKGROUPS pfnOnNewTalkgroups,
                            PFN_MAGELLAN_ON_MODIFIED_TALKGROUPS pfnOnModifiedTalkgroups,
                            PFN_MAGELLAN_ON_REMOVED_TALKGROUPS pfnOnRemovedTalkgroups,
                            const void *userData);

#ifdef __cplusplus
}
#endif
#endif
